const KEY="equb-circle-v1",$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],id=()=>crypto.randomUUID();
const seed={round:1,members:[{id:id(),name:"Meron Bekele",phone:"+251 91 234 5678",amount:1000,paid:true,received:false},{id:id(),name:"Dawit Alemu",phone:"+251 92 345 6789",amount:1000,paid:true,received:false},{id:id(),name:"Hana Tesfaye",phone:"+251 93 456 7890",amount:1000,paid:false,received:false},{id:id(),name:"Samuel Girma",phone:"+251 94 567 8901",amount:1000,paid:false,received:false}],history:[],deadline:nextDeadline()};let state=load();
function nextDeadline(){const d=new Date();d.setDate(d.getDate()+7);return d.toISOString().slice(0,10)}function load(){try{const v=JSON.parse(localStorage.getItem(KEY));if(v&&Array.isArray(v.members))return v}catch(e){console.warn(e)}return seed}function save(){localStorage.setItem(KEY,JSON.stringify(state))}function esc(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}function etb(v){return new Intl.NumberFormat("en-US").format(v)+" ETB"}function initials(n){return n.split(/\s+/).map(x=>x[0]).slice(0,2).join("").toUpperCase()}function deadline(){return new Date(state.deadline+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"})}
function stats(){const paid=state.members.filter(m=>m.paid),total=state.members.reduce((a,m)=>a+m.amount,0),collected=paid.reduce((a,m)=>a+m.amount,0),percent=state.members.length?Math.round(paid.length/state.members.length*100):0,distributed=state.history.reduce((a,r)=>a+r.pot,0);$("#roundNo").textContent=state.round;$("#bannerRound").textContent=state.round;$("#memberCount").textContent=state.members.length;$("#collected").textContent=etb(collected);$("#collectionNote").textContent=percent+"% complete";$("#dueDate").textContent=deadline();$("#deadlineText").textContent="Deadline · "+deadline();$("#distributed").textContent=etb(distributed);$("#heroPot").textContent=etb(total);$("#heroProgress").style.width=percent+"%";$("#roundProgress").style.width=percent+"%";$("#heroStatus").textContent=`${paid.length} of ${state.members.length} paid`;$("#paidCount").textContent=paid.length;$("#draw").disabled=!state.members.length||paid.length!==state.members.length}
function contributions(){$("#contributionList").innerHTML=state.members.length?state.members.map(m=>`<article class="member-pay"><b class="avatar">${initials(m.name)}</b><div><strong>${esc(m.name)}</strong><small>${etb(m.amount)} contribution</small></div><span class="status ${m.paid?"paid":"pending"}">${m.paid?"✓ Paid":"Pending"}</span></article>`).join(""):'<div class="empty">Add members to begin the round.</div>'}
function members(){const q=$("#search").value.trim().toLowerCase(),list=state.members.filter(m=>m.name.toLowerCase().includes(q)||m.phone.includes(q));$("#memberRows").innerHTML=list.map((m,i)=>`<tr><td><div class="person"><b class="avatar">${initials(m.name)}</b><strong>${esc(m.name)}</strong></div></td><td>${esc(m.phone)}</td><td>${etb(m.amount)}</td><td><span class="status ${m.paid?"paid":"pending"}">${m.paid?"Paid":"Pending"}</span></td><td><span class="pill">${m.received?"Received":`#${state.members.filter(x=>!x.received).findIndex(x=>x.id===m.id)+1}`}</span></td><td><button class="remove" data-remove="${m.id}">Remove</button></td></tr>`).join("");$("#memberEmpty").hidden=!!list.length;$(".table-wrap").hidden=!list.length}
function payouts(){const ordered=[...state.members.filter(m=>!m.received),...state.members.filter(m=>m.received)];$("#payoutList").innerHTML=ordered.length?ordered.map((m,i)=>`<article class="payout ${m.received?"done":""}"><i>${m.received?"✓":String(i+1).padStart(2,"0")}</i><b class="avatar">${initials(m.name)}</b><div><strong>${esc(m.name)}</strong><small>${m.received?"Payout received":"Eligible for a future draw"}</small></div></article>`).join(""):'<div class="empty-history">No members yet.</div>'}
function history(){const list=[...state.history].reverse();$("#roundHistory").innerHTML=list.length?list.map(r=>`<article class="history-row"><i>✦</i><div><strong>Round ${r.round} · ${esc(r.winner)}</strong><small>${new Date(r.date).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</small></div><aside><strong>${etb(r.pot)}</strong><small>distributed</small></aside></article>`).join(""):'<div class="empty-history">Completed rounds will appear here.</div>'}
function payments(){$("#paymentList").innerHTML=state.members.length?state.members.map(m=>`<label class="payment-option"><input type="checkbox" data-pay="${m.id}" ${m.paid?"checked":""}><b class="avatar">${initials(m.name)}</b><strong>${esc(m.name)}</strong><span>${etb(m.amount)}</span></label>`).join(""):'<div class="empty-history">Add members before recording payments.</div>'}function render(){stats();contributions();members();payouts();history();payments()}
function open(mid){$("#"+mid).hidden=false}function close(mid){$("#"+mid).hidden=true}function toast(t){const el=$("#toast");el.textContent=t;el.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove("show"),2600)}
$("#memberForm").onsubmit=e=>{e.preventDefault();const name=$("#name").value.trim(),phone=$("#phone").value.trim(),amount=Number($("#amount").value);if(state.members.some(m=>m.phone.replace(/\D/g,"")===phone.replace(/\D/g,""))){$("#memberError").textContent="A member with that phone number already exists.";return}const member={id:id(),name,phone,amount,paid:false,received:false};$("#order").value==="next"?state.members.unshift(member):state.members.push(member);save();e.target.reset();$("#amount").value=state.members[0]?.amount||1000;close("memberModal");render();toast(`${name} joined the circle.`)};
$("#savePayments").onclick=()=>{$$("[data-pay]").forEach(box=>{const m=state.members.find(m=>m.id===box.dataset.pay);if(m)m.paid=box.checked});save();close("paymentModal");render();toast("Contributions updated.")};
$("#draw").onclick=()=>{const eligible=state.members.filter(m=>!m.received);if(!eligible.length){state.members.forEach(m=>m.received=false);toast("A new payout rotation has started.");render();return}const winner=eligible[Math.floor(Math.random()*eligible.length)],pot=state.members.reduce((a,m)=>a+m.amount,0),record={round:state.round,winner:winner.name,pot,date:Date.now()};winner.received=true;state.history.push(record);state.round++;state.members.forEach(m=>m.paid=false);state.deadline=nextDeadline();save();$("#winnerName").textContent=winner.name;$("#winnerText").textContent=`has been selected to receive the Round ${record.round} pot.`;$("#winnerReceipt").innerHTML=`<div><span>Round</span><strong>${record.round}</strong></div><div><span>Contributors</span><strong>${state.members.length}</strong></div><div><span>Payout</span><strong>${etb(pot)}</strong></div><div><span>Date</span><strong>${new Date().toLocaleDateString()}</strong></div>`;open("winnerModal");render()};
document.addEventListener("click",e=>{const c=e.target.closest("[data-close]")?.dataset.close;if(c)close(c);const rid=e.target.closest("[data-remove]")?.dataset.remove;if(rid&&confirm("Remove this member from the circle?")){state.members=state.members.filter(m=>m.id!==rid);save();render();toast("Member removed.")}});$$('.open-member').forEach(b=>b.onclick=()=>{$("#memberError").textContent="";open("memberModal")});$(".open-payment").onclick=()=>{payments();open("paymentModal")};$("#search").oninput=members;$("#menu").onclick=()=>$("#side").classList.toggle("open");$$('nav a').forEach(a=>a.onclick=()=>$("#side").classList.remove("open"));$$('.backdrop').forEach(b=>b.onclick=e=>{if(e.target===b)b.hidden=true});document.onkeydown=e=>{if(e.key==="Escape")$$('.backdrop').forEach(x=>x.hidden=true)};$("#print").onclick=()=>print();
$("#copySummary").onclick=async()=>{const paid=state.members.filter(m=>m.paid).length,text=`Equb Round ${state.round}: ${paid}/${state.members.length} members paid. Current pot: ${etb(state.members.reduce((a,m)=>a+m.amount,0))}. Deadline: ${deadline()}.`;await navigator.clipboard.writeText(text);toast("Round summary copied.")};$("#clearHistory").onclick=()=>{if(state.history.length&&confirm("Clear completed round history?")){state.history=[];save();render();toast("Round history cleared.")}};
$("#export").onclick=()=>{const rows=[["Name","Phone","Contribution","Paid this round","Payout received"],...state.members.map(m=>[m.name,m.phone,m.amount,m.paid?"Yes":"No",m.received?"Yes":"No"])],csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`equb-round-${state.round}.csv`;a.click();URL.revokeObjectURL(a.href);toast("Records exported.")};
const d=new Date();$("#date").textContent=d.toLocaleDateString("en-US",{weekday:"long",month:"short",day:"numeric"}).toUpperCase();render();
